import "./globals.css";

import { Public_Sans } from "next/font/google";

import Container from "@/components/layout/container";
import Navbar from "@/components/layout/navbar";
import ThemeSwitch from "@/components/theme-switch";
import { Toaster } from "@/components/ui/toast/toaster";
import { ThemeProvider } from "@/context/theme-provider";

const font = Public_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      <body className={font.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
